import "@uploadthing/react/styles.css";
import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { GeistSans } from "geist/font/sans";
import { Toaster } from "sonner";
import { extractRouterConfig } from "uploadthing/server";
import { TopNav } from "~/app/_components/topnav";
import { ourFileRouter } from "~/app/api/uploadthing/core";

export const metadata = {
  title: "Tiny galery tutorial",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="dark">
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <div className="h-screen grid grid-rows-[auto,1fr]">
            <TopNav />
            <main className="overflow-y-scroll">{children}</main>
          </div>
          {modal}
          <div id="modal-root" />
          <Toaster theme="dark" />
        </body>
      </html>
    </ClerkProvider>
  );
}
